// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace F16.StreamedTextures
{

public enum TextureIdentifier : sbyte
{
  None = 0,
  MFD_L = 1,
  MFD_R = 2,
  DED = 5,
  RWR = 6,
};


}
