// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace F16.StreamedTextures
{

public enum TextureCompression : sbyte
{
  None = 0,
  PNG = 1,
};


}
