-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Icp

local IcpKey = {
    NoKey = 0,
    Com1 = 1,
    Com2 = 2,
    Iff = 3,
    List = 4,
    AA = 5,
    AG = 6,
    BTN_0 = 10,
    BTN_1 = 11,
    BTN_2 = 12,
    BTN_3 = 13,
    BTN_4 = 14,
    BTN_5 = 15,
    BTN_6 = 16,
    BTN_7 = 17,
    BTN_8 = 18,
    BTN_9 = 19,
}

return IcpKey -- return the module