-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Icp

local flatbuffers = require('flatbuffers')

local KeyPress = {} -- the module
local KeyPress_mt = {} -- the class metatable

function KeyPress.New()
    local o = {}
    setmetatable(o, {__index = KeyPress_mt})
    return o
end
function KeyPress_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function KeyPress_mt:Key()
    return self.view:Get(flatbuffers.N.Int8, self.view.pos + 0)
end
function KeyPress_mt:EventCounter()
    return self.view:Get(flatbuffers.N.Int64, self.view.pos + 8)
end
function KeyPress.CreateKeyPress(builder, key, eventCounter)
    builder:Prep(8, 16)
    builder:PrependInt64(eventCounter)
    builder:Pad(7)
    builder:PrependInt8(key)
    return builder:Offset()
end

return KeyPress -- return the module