-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: StreamedTextures

local TextureCompression = {
    None = 0,
    PNG = 1,
}

return TextureCompression -- return the module