-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: StreamedTextures

local TextureIdentifier = {
    None = 0,
    MFD_L = 1,
    MFD_R = 2,
    DED = 5,
    RWR = 6,
}

return TextureIdentifier -- return the module